const mockData = [
  {
  id: 1,
  name: "Dr. Ramesh Sharma",
  role: "doctor",
  department: "Cardiology",
  contact: "9876543210",
  available: true,
  photo: "/images/reception.jpg",
  email: "ramesh.sharma@hospital.com",
  experience: 12,
  qualifications: "MBBS, MD",
  shift: "9 AM - 5 PM",
  appointments: {
    "2025-09-12": [
      { patient: "Amit Verma", time: "10:00 AM" },
      { patient: "Sneha Patel", time: "11:30 AM" }
    ],
    "2025-09-13": [
      { patient: "Rahul Mehra", time: "2:00 PM" }
    ]
  }
}
,
  {
    id: 2,
    name: "Nurse Kavita",
    role: "nurse",
    department: "Pediatrics",
    contact: "9123456789",
    available: true,
    photo: "/images/hospital-bg.jpg",
    email: "kavita@hospital.com",
    experience: 6,
    qualifications: "BSc Nursing",
    shift: "Morning",
  },
  {
    id: 3,
    name: "Ravi Kumar",
    role: "ambulance",
    department: "Emergency",
    contact: "9988776655",
    available: true,
    photo: "/images/reception.jpg",
    email: "ravi@hospital.com",
    experience: 4,
    qualifications: "EMT Certified",
    shift: "24/7",
  },

  // Additional Doctors
  {
    id: 4,
    name: "Dr. Priya Mehta",
    role: "doctor",
    department: "Neurology",
    contact: "9012345678",
    available: true,
    photo: "/images/hospital-bg.jpg",
    email: "priya.mehta@hospital.com",
    experience: 10,
    qualifications: "MBBS, DM Neurology",
    shift: "10 AM - 6 PM",
  },
  {
    id: 5,
    name: "Dr. Anil Verma",
    role: "doctor",
    department: "Orthopedics",
    contact: "9345678901",
    available: false,
    photo: "/images/reception.jpg",
    email: "anil.verma@hospital.com",
    experience: 8,
    qualifications: "MBBS, MS Ortho",
    shift: "11 AM - 7 PM",
  },
  {
    id: 6,
    name: "Dr. Sneha Iyer",
    role: "doctor",
    department: "Gynecology",
    contact: "9786543210",
    available: true,
    photo: "/images/window.svg",
    email: "sneha.iyer@hospital.com",
    experience: 14,
    qualifications: "MBBS, MS Gynecology",
    shift: "8 AM - 4 PM",
  },

  // Additional Nurses
  {
    id: 7,
    name: "Nurse Rohit Singh",
    role: "nurse",
    department: "ICU",
    contact: "9456123789",
    available: true,
    photo: "/images/globe.svg",
    email: "rohit.singh@hospital.com",
    experience: 7,
    qualifications: "GNM Nursing",
    shift: "Night",
  },
  {
    id: 8,
    name: "Nurse Aditi Joshi",
    role: "nurse",
    department: "Maternity",
    contact: "9234567890",
    available: false,
    photo: "/images/next.svg",
    email: "aditi.joshi@hospital.com",
    experience: 5,
    qualifications: "BSc Nursing",
    shift: "Evening",
  },

  // Additional Ambulance Staff
  {
    id: 9,
    name: "Suresh Patil",
    role: "ambulance",
    department: "Emergency",
    contact: "9765432109",
    available: true,
    photo: "/images/vercel.svg",
    email: "suresh.patil@hospital.com",
    experience: 6,
    qualifications: "Paramedic",
    shift: "24/7",
  },
  {
    id: 10,
    name: "Anita Deshmukh",
    role: "ambulance",
    department: "Emergency",
    contact: "9341256780",
    available: false,
    photo: "/images/file.svg",
    email: "anita.deshmukh@hospital.com",
    experience: 3,
    qualifications: "EMT Certified",
    shift: "Day",
  },
];

export default mockData;
